=== codeforsanjose/211chatbot/botpress/data/assets/modules/basic-skills/config.schema.json
{
  "type": "object",
  "properties": {
    "defaultContentElement": {
      "default": "builtin_single-choice",
      "type": "string"
    },
    "defaultContentRenderer": {
      "default": "#builtin_single-choice",
      "type": "string"
    },
    "defaultMaxAttempts": {
      "default": 3,
      "type": "number"
    },
    "disableIntegrityCheck": {
      "default": true,
      "type": "boolean"
    },
    "matchNumbers": {
      "default": true,
      "type": "boolean"
    },
    "matchNLU": {
      "default": true,
      "type": "boolean"
    },
    "transportConnectionString": {
      "description": "Nodemailer2 transport connection string.",
      "see": "https://nodemailer.com/smtp/#examples",
      "example": "smtps://user%40gmail.com:pass",
      "default": "<<change me>>"
    },
    "$schema": {
      "type": "string"
    }
  },
  "additionalProperties": false,
  "required": [
    "defaultContentElement",
    "defaultContentRenderer",
    "defaultMaxAttempts",
    "disableIntegrityCheck",
    "matchNLU",
    "matchNumbers",
    "transportConnectionString"
  ],
  "$schema": "http://json-schema.org/draft-07/schema#"
}

=== codeforsanjose/211chatbot/botpress/data/global/config/basic-skills.json
{
  "$schema": "../../assets/modules/basic-skills/config.schema.json",
  "defaultContentElement": "builtin_single-choice",
  "defaultContentRenderer": "#builtin_single-choice",
  "defaultMaxAttempts": 3,
  "disableIntegrityCheck": true,
  "matchNumbers": true,
  "matchNLU": true,
  "transportConnectionString": "<<change me>>"
}
